### ISSUE TITLE
Auto-migration for agents/configs/sources for refactored storage 

### ISSUE THREAD

**Issue by sarahwooders** [letta-ai/letta#767]
Storage refactoring introduced in  #708 will cause backward compatibility issues for existing configurations, data sources, and agents. Before the next release, we need add scripts to automatically migrate agents 

We can automatically run migration on `memgpt run`: 
```
> memgpt run 
? Older versions of agents and data sources detected. Run auto-migrate? [Y/n]
```
We can also allow manually migrating with 
```
> memgpt migrate 
```

## Todos 
- [ ] Add `memgpt migrate` CLI function (function also called with new `memgpt run`)
  - [ ] Migrate MemGPT config info (make sure old configs don't break) 
  - [ ] Migrate agent config 
  - [ ] Migrate agent recall memory 
  - [ ] Migrate agent archival memory 
  - [ ] Migrate loaded data sources 
- [ ] Add tests with reference version of: 
  - [ ] Config file 
  - [ ] Data sources 
  - [ ] Agents state + config 

## Config Migration  
For example, prior versions of the config file with throw this error since there is no more "local" archival memory: 
```
  File "/Users/sarahwooders/repos/memgpt-main/MemGPT/memgpt/persistence_manager.py", line 54, in __init__
    self.archival_memory = EmbeddingArchivalMemory(agent_config)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sarahwooders/repos/memgpt-main/MemGPT/memgpt/memory.py", line 370, in __init__
    self.storage = StorageConnector.get_archival_storage_connector(agent_config=agent_config)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sarahwooders/repos/memgpt-main/MemGPT/memgpt/connectors/storage.py", line 145, in get_archival_storage_connector
    return StorageConnector.get_storage_connector(TableType.ARCHIVAL_MEMORY, agent_config=agent_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sarahwooders/repos/memgpt-main/MemGPT/memgpt/connectors/storage.py", line 133, in get_storage_connector
    return InMemoryStorageConnector(agent_config=agent_config, table_type=table_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sarahwooders/repos/memgpt-main/MemGPT/memgpt/connectors/local.py", line 182, in __init__
    raise ValueError(f"Table type {table_type} not supported by InMemoryStorageConnector")
ValueError: Table type archival_memory not supported by InMemoryStorageConnector
```
