### ISSUE TITLE
Usability improvements for dynamic functions

### ISSUE THREAD

**Issue by tombedor** [letta-ai/letta#812]
A few changes to make it easier and friendlier to add custom functions:

- [ ] Validations script: add a utility to validate that functions are defined correctly, with type hints and doc strings. Link to resources about what these are.

- [ ] System message to AI for slash commands: when running a slash command, send output to AI as a system message. This enables the agent to understand what is happening in the background, and prevent the scenario where a slash command is run, and the agent receives consecutive heartbeats - often resulting in internal monologue like "hm no response still, I will wait and be helpful"

- [ ] Some meta-functions to core library: add_function, remove_function, list_function: https://github.com/tombedor/youbot/tree/main/youbot/memgpt_extensions/functions/meta_functions. Add a dynamic_function preset (perhaps a persona as well?)

- [ ] Documentation

**Comment by tombedor** [comment]
@cpacker filing this as a reminder to myself, plz feel free to assign to me

**Comment by tombedor** [comment]
One more tweak I think would be good is to tweak system commands so that they send a notif to the agent.. right now I think the agent gets a redundant heartbeat and has internal monologue like "hm no response, I'll just keep ready to be helpful"
